network_name: "ActuatorNet"
file_path: "data_sets/merged_motor_data_ultimate_pro_max_plus.json"
device: "cpu"

algo:
  name: "SupervisedLearning"
  history_length: &base 15
  batch_size: 32
  num_learning_epochs: 50
  num_testing_epochs: 400
  clip_param: 0.2
  learning_rate: 0.001
  weight_decay: 0.0001
  max_grad_norm: 1.0
  shuffle: False

net:
  half_input_size: *base
  output_size: 1
  hidden_size: [32, 128, 64, 32, 16]

runner:
  save_interval: 5
  save_dir: "checkpoints/calf_batch32"
  log_dir: "logs"